spring:
  datasource:
    url: jdbc:postgresql://ample-molerat-4741.6wr.cockroachlabs.cloud:26257/roach_data?sslmode=require&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory
    username: Jem
    password: -rGoRDzowiOylPJ6k9afyg
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=true
        hbm2ddl:
          auto: update
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true