spring:
  datasource:
    url: jdbc:postgresql://ample-molerat-4741.6wr.cockroachlabs.cloud:26257/roach_data?sslmode=verify-full&sslrootcert=C:\Users\Joshu\AppData\Roaming\postgresql\root.crt
    username: Jem
    password: -rGoRDzowiOylPJ6k9afyg
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=true
        hbm2ddl:
          auto: create
        default_schema: nwHacks
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect